name: 'Update Node'
on: workflow_dispatch
jobs:
  update_node:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        run: |
             echo "currentDate=$(date +'%Y%m%d')" >> $GITHUB_ENV
             echo "currentMouth=$(date +'%m')" >> $GITHUB_ENV
             echo "currentYear=$(date +'%Y')" >> $GITHUB_ENV
      - name: Checkout    # 获取分支的代码和提交记录
        uses: actions/checkout@v2
      - name: Downlod file
        shell: bash
        run: |
             curl 'https://v2rayshare.com/wp-content/uploads/${{env.currentYear}}/${{env.currentMouth}}/${{env.currentDate}}.yam' -o temp.yaml
             ls .
